# Generated by Django 2.2.4 on 2019-08-07 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190807_1351'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Servicios',
            new_name='Services',
        ),
    ]
