# Generated by Django 2.2.4 on 2019-08-12 14:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190812_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='contenido',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
